/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package detect.theme;

import detect.theme.Service.Calcul;
import detect.theme.Service.Indi_Perf;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author pc
 */
public class JFrameTestCorpus extends javax.swing.JFrame {
    File file;


    /**
     * Creates new form JFrameTestCorpus
     */
    public JFrameTestCorpus() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        affichage = new javax.swing.JTextField();
        jButtonExa3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ExaText = new javax.swing.JTextField();
        jButtonExa = new javax.swing.JButton();
        PreText = new javax.swing.JTextField();
        jButtonRappel = new javax.swing.JButton();
        jButtonPrécision = new javax.swing.JButton();
        RapText = new javax.swing.JTextField();
        jButtonFmesure = new javax.swing.JButton();
        FmesText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        matconf = new javax.swing.JTable();

        affichage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affichageActionPerformed(evt);
            }
        });

        jButtonExa3.setText("=");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Détecteur de thème");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Exactitude");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Matrice de confusion pour les mots");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("F-mesure");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rappel");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Précision");

        ExaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExaTextActionPerformed(evt);
            }
        });

        jButtonExa.setText("=");
        jButtonExa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExaActionPerformed(evt);
            }
        });

        PreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreTextActionPerformed(evt);
            }
        });

        jButtonRappel.setText("=");
        jButtonRappel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRappelActionPerformed(evt);
            }
        });

        jButtonPrécision.setText("=");
        jButtonPrécision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrécisionActionPerformed(evt);
            }
        });

        RapText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RapTextActionPerformed(evt);
            }
        });

        jButtonFmesure.setText("=");
        jButtonFmesure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFmesureActionPerformed(evt);
            }
        });

        FmesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FmesTextActionPerformed(evt);
            }
        });

        matconf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"culture", "19", "0", "0", "1", "0"},
                {"economie", "0", "20", "0", "0", "0"},
                {"politique", "0", "1", "18", "1", "0"},
                {"scences_technologie", "0", "0", "1", "19", "0"},
                {"sport", "0", "0", "0", "0", "20"}
            },
            new String [] {
                "v-observée/v-réelle", "culture", "economie", "politique", "sciences_technologie", "sport"
            }
        ));
        jScrollPane1.setViewportView(matconf);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonExa)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonFmesure)
                                    .addComponent(jButtonRappel)
                                    .addComponent(jButtonPrécision))
                                .addGap(0, 37, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FmesText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExaText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RapText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PreText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExa)
                    .addComponent(ExaText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRappel)
                    .addComponent(RapText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrécision)
                    .addComponent(PreText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFmesure)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FmesText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void affichageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affichageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_affichageActionPerformed

    private void ExaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExaTextActionPerformed

    private void jButtonExaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExaActionPerformed
        File f_test_mot=new File("src\\main\\java\\detect\\theme\\LesCorpus\\Corpus_Mots_XML\\Corpus_test_XML");  
        File vec_theme_mot=new File("src\\main\\java\\detect\\theme\\LesCorpus\\Corpus_Mots_XML\\Vecteur_theme");
        int [][] matrice=null;
        try {      
            matrice = Indi_Perf.matriceconfusion(f_test_mot,vec_theme_mot);
        } catch (IOException ex) {
            Logger.getLogger(JFrameTestCorpus.class.getName()).log(Level.SEVERE, null, ex);
        }
        float exa = Indi_Perf.Exactitude(matrice, (int) Calcul.number_of_files(f_test_mot));
        ExaText.setText(Float.toString(exa));
        System.out.println("exactitude "+exa);
        
    }//GEN-LAST:event_jButtonExaActionPerformed

    private void PreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreTextActionPerformed

    private void jButtonRappelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRappelActionPerformed
        File f_test_mot=new File("src\\main\\java\\detect\\theme\\LesCorpus\\Corpus_Mots_XML\\Corpus_test_XML");  
        File vec_theme_mot=new File("src\\main\\java\\detect\\theme\\LesCorpus\\Corpus_Mots_XML\\Vecteur_theme");
        int [][] matrice=null;
        try {      
            matrice = Indi_Perf.matriceconfusion(f_test_mot,vec_theme_mot);
        } catch (IOException ex) {
            Logger.getLogger(JFrameTestCorpus.class.getName()).log(Level.SEVERE, null, ex);
        }
        double rap = Indi_Perf.RappelGlobal(matrice);
        RapText.setText(Double.toString(rap));
        System.out.println("rappel "+Double.toString(rap));
    }//GEN-LAST:event_jButtonRappelActionPerformed

    private void jButtonPrécisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrécisionActionPerformed
        File f_test_mot=new File("src\\main\\java\\detect\\theme\\LesCorpus\\Corpus_Mots_XML\\Corpus_test_XML");  
        File vec_theme_mot=new File("src\\main\\java\\detect\\theme\\LesCorpus\\Corpus_Mots_XML\\Vecteur_theme");
        int [][] matrice=null;
        try {      
            matrice = Indi_Perf.matriceconfusion(f_test_mot,vec_theme_mot);
        } catch (IOException ex) {
            Logger.getLogger(JFrameTestCorpus.class.getName()).log(Level.SEVERE, null, ex);
        }
        double pre = Indi_Perf.PrecisionGlobal(matrice);
        PreText.setText(Double.toString(pre));
        System.out.println("precision "+Double.toString(pre));    }//GEN-LAST:event_jButtonPrécisionActionPerformed

    private void RapTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RapTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RapTextActionPerformed

    private void jButtonFmesureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFmesureActionPerformed
        File f_test_mot=new File("src\\main\\java\\detect\\theme\\LesCorpus\\Corpus_Mots_XML\\Corpus_test_XML");  
        File vec_theme_mot=new File("src\\main\\java\\detect\\theme\\LesCorpus\\Corpus_Mots_XML\\Vecteur_theme");
        int [][] matrice=null;
        try {      
            matrice = Indi_Perf.matriceconfusion(f_test_mot,vec_theme_mot);
        } catch (IOException ex) {
            Logger.getLogger(JFrameTestCorpus.class.getName()).log(Level.SEVERE, null, ex);
        }
        double Fmesure = Indi_Perf.FmesureGlobal(matrice);
        FmesText.setText(Double.toString(Fmesure));
        System.out.println("precision "+Double.toString(Fmesure));
    }//GEN-LAST:event_jButtonFmesureActionPerformed

    private void FmesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FmesTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FmesTextActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ExaText;
    private javax.swing.JTextField FmesText;
    private javax.swing.JTextField PreText;
    private javax.swing.JTextField RapText;
    private javax.swing.JTextField affichage;
    private javax.swing.JButton jButtonExa;
    private javax.swing.JButton jButtonExa3;
    private javax.swing.JButton jButtonFmesure;
    private javax.swing.JButton jButtonPrécision;
    private javax.swing.JButton jButtonRappel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable matconf;
    // End of variables declaration//GEN-END:variables
}
